api_login_check:
  path: /api/login_check

register:
  path: /api/register
  controller: App\Controller\AuthController::register
  methods: POST

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
